Ticket5783 parking sequence
ISISComputingGroup/EPICS-refl pull request #23
Opened 2020-12-13 14:14 UTC by John-Holt-Tessella

https://github.com/ISISComputingGroup/IBEX/issues/5783

2020-12-18 17:32 UTC, ThomasLohnert requested changes
Looks good!

There seems to be an issue with move synchronization when you move two axes in a sequence. The axes will move synchronously to the first step in the sequence, but not for the rest. I don't know how much we care but I think we should define the behaviour, ie. either synchronise all the steps or don't synchronise it at all. At the end of the whole sequence the server also throws the error that says the velocity for this axis has previously been restored, let's get rid of that

2020-12-18 17:32 UTC, ThomasLohnert commented on ReflectometryServer/test_modules/utils.py
> +def no_autosave(func):
Awesome!

2021-01-05 14:56 UTC, John-Holt-Tessella commented on ReflectometryServer/axis.py
> +    parking_sequence: Optional[int]  # the parking sequence we are at the end of
see https://github.com/ISISComputingGroup/EPICS-refl/pull/23/files/524eacd958239a44eb08d2c1df7041bbb075fe84#diff-c24982c71051485fde2eca3c6778b9ae3d9fbd10c3e99d8d0503da8e054477faR290

```
For RBV set the index of the parking sequence index just reached by the motor; These must be generated in order
For SP set the index of the parking sequence the motor should be going to
```

2021-01-06 11:22 UTC, John-Holt-Tessella commented on ReflectometryServer/exceptions.py
> +class BeamlineConfigurationParkAutosaveInvalidException(Exception):
Add documentation to https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Reflectometry-Troubleshooting-and-FAQ

2021-01-06 17:57 UTC, John-Holt-Tessella commented
Turns out ticket to make velocity cache warning better had different implementation so I have used that instead of removing it as we spoke about (sorry)

2021-01-08 15:49 UTC, ThomasLohnert requested changes
Found some odd behaviour using a config that has a component with the following defined parking behaviour:
```
    add_driver(IocDriver(test_component, ChangeAxis.HEIGHT, MotorPVWrapper("MOT:MTR0107"),
                         out_of_beam_positions=[OutOfBeamSequence([2, -4])]))
    add_driver(IocDriver(test_component, ChangeAxis.PHI, MotorPVWrapper("MOT:MTR0108"),
                         out_of_beam_positions=[OutOfBeamSequence([3, -6])]))
```

1. Move component out of beam
2. Restart IOC
3. Set inbeam param to `IN` and move parameter individually --> Axes do not move (would expect them to go to intermediate park position, then to their offset SPs)
4. Set inbeam param to `OUT` --> Axes go to intermediate step, then back to their initial out position (would expect them not to move, but this is less critical)
5. Set inbeam param to `IN` and move all --> parking axes go straight to axis offset SPs (would expect them to go to intermediate park position, then to their offset SPs)

2021-01-12 15:15 UTC, ThomasLohnert approved these changes

2021-01-12 15:15 UTC, merged